apiVersion: batch/v1
kind: CronJob
metadata:
  name: clear-sessions
spec:
  startingDeadlineSeconds: 100000
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: clear-sessions
            envFrom :
            - secretRef :
                name : django-secrets
            image: fergoth/k8s_2:sha256:79ae6a0a6f65a09e9ca8626f39d190fb13b6c68d6d7935755fcc5422cf9084b3
            command:
            - /bin/sh
            - -c
            - python manage.py clearsessions
          restartPolicy: Never