apiVersion : v1
kind : Service
metadata :
  namespace: edu-andrey-trefilov
  labels :
    app : django
  name : django-service
spec :
  type : ClusterIP
  selector :
    app : django
  ports :
    - port : 8000
      targetPort : 80