apiVersion : apps/v1
kind : Deployment
metadata :
  name : django-deploy
  labels :
    app : django-nunit
spec :
  selector:
    matchLabels:
      app : django
  template :
    metadata :
      labels :
        app : django
    spec :    
      containers :
      - name : django-nunit-container
        image : django_app:latest
        imagePullPolicy : Never
        envFrom :
        - secretRef :
            name : django-secrets
        env:
        - name : DEBUG
          value : '1'
        ports :
        - containerPort : 80

